export const CODE_LIST_REQUEST = 'CODE_LIST_REQUEST'
export const CODE_LIST_SUCCESS = 'CODE_LIST_SUCCESS'
export const CODE_LIST_FAIL = 'CODE_LIST_FAIL'

export const CODE_CREATE_REQUEST = 'CODE_CREATE_REQUEST'
export const CODE_CREATE_SUCCESS = 'CODE_CREATE_SUCCESS'
export const CODE_CREATE_FAIL = 'CODE_CREATE_FAIL'
export const CODE_CREATE_RESET = 'CODE_CREATE_RESET'

export const CODE_DETAIL_REQUEST = 'CODE_DETAIL_REQUEST'
export const CODE_DETAIL_SUCCESS = 'CODE_DETAIL_SUCCESS'
export const CODE_DETAIL_FAIL = 'CODE_DETAIL_FAIL'
export const CODE_DETAIL_RESET = 'CODE_DETAIL_RESET'

export const CODE_UPDATE_REQUEST = 'CODE_UPDATE_REQUEST'
export const CODE_UPDATE_SUCCESS = 'CODE_UPDATE_SUCCESS'
export const CODE_UPDATE_FAIL = 'CODE_UPDATE_FAIL'
export const CODE_UPDATE_RESET = 'CODE_UPDATE_RESET'

export const CODE_DELETE_REQUEST = 'CODE_DELETE_REQUEST'
export const CODE_DELETE_SUCCESS = 'CODE_DELETE_SUCCESS'
export const CODE_DELETE_FAIL = 'CODE_DELETE_FAIL'
export const CODE_DELETE_RESET = 'CODE_DELETE_RESET'
