export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAIL_RESET = 'ORDER_DETAIL_RESET'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_CASH_REQUEST = 'ORDER_CASH_REQUEST'
export const ORDER_CASH_SUCCESS = 'ORDER_CASH_SUCCESS'
export const ORDER_CASH_FAIL = 'ORDER_CASH_FAIL'
export const ORDER_CASH_RESET = 'ORDER_CASH_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'

export const ORDER_CONSULT_REQUEST = 'ORDER_CONSULT_REQUEST'
export const ORDER_CONSULT_SUCCESS = 'ORDER_CONSULT_SUCCESS'
export const ORDER_CONSULT_FAIL = 'ORDER_CONSULT_FAIL'

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST'
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS'
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL'
export const ORDER_UPDATE_RESET = 'ORDER_UPDATE_RESET'

export const ORDER_UPDATE_BY_MEMBER_REQUEST = 'ORDER_UPDATE_BY_MEMBER_REQUEST'
export const ORDER_UPDATE_BY_MEMBER_SUCCESS = 'ORDER_UPDATE_BY_MEMBER_SUCCESS'
export const ORDER_UPDATE_BY_MEMBER_FAIL = 'ORDER_UPDATE_BY_MEMBER_FAIL'
export const ORDER_UPDATE_BY_MEMBER_RESET = 'ORDER_UPDATE_BY_MEMBER_RESET'

export const ORDER_FILTER_REQUEST = 'ORDER_FILTER_REQUEST'
export const ORDER_FILTER_SUCCESS = 'ORDER_FILTER_SUCCESS'
export const ORDER_FILTER_FAIL = 'ORDER_FILTER_FAIL'
export const ORDER_FILTER_RESET = 'ORDER_FILTER_RESET'

export const ORDERS_SHIPPER_REQUEST = 'ORDERS_SHIPPER_REQUEST'
export const ORDERS_SHIPPER_SUCCESS = 'ORDERS_SHIPPER_SUCCESS'
export const ORDERS_SHIPPER_FAIL = 'ORDERS_SHIPPER_FAIL'

export const SHIPPER_UPDATE_ORDER_REQUEST = 'SHIPPER_UPDATE_ORDER_REQUEST'
export const SHIPPER_UPDATE_ORDER_SUCCESS = 'SHIPPER_UPDATE_ORDER_SUCCESS'
export const SHIPPER_UPDATE_ORDER_FAIL = 'SHIPPER_UPDATE_ORDER_FAIL'
export const SHIPPER_UPDATE_ORDER_RESET = 'SHIPPER_UPDATE_ORDER_RESET'

export const CHOOSE_SHIPPER_SUCCESS = 'CHOOSE_SHIPPER_SUCCESS'
export const CHOOSE_SHIPPER_RESET = 'CHOOSE_SHIPPER_RESET'
