export const LIST_REVIEWS_REQUEST = 'LIST_REVIEWS_REQUEST';
export const LIST_REVIEWS_SUCCESS = 'LIST_REVIEWS_SUCCESS';
export const LIST_REVIEWS_FAIL = 'LIST_REVIEWS_FAIL';

export const APPROVE_STATUS_REQUEST = 'APPROVE_STATUS_REQUEST';
export const APPROVE_STATUS_SUCCESS = 'APPROVE_STATUS_SUCCESS';
export const APPROVE_STATUS_FAIL = 'APPROVE_STATUS_FAIL';
export const APPROVE_STATUS_RESET = 'APPROVE_STATUS_RESET';

export const DELETE_STATUS_REQUEST = 'DELETE_STATUS_REQUEST';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAIL = 'DELETE_STATUS_FAIL';
export const DELETE_STATUS_RESET = 'DELETE_STATUS_RESET';

export const FILTER_REVIEW_REQUEST = 'FILTER_REVIEW_REQUEST';
export const FILTER_REVIEW_SUCCESS = 'FILTER_REVIEW_SUCCESS';
export const FILTER_REVIEW_FAIL = 'FILTER_REVIEW_FAIL';
export const FILTER_REVIEW_RESET = 'FILTER_REVIEW_RESET';
