export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const CREATE_USER_RESET = 'CREATE_USER_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_LOGIN_GOOGLE_REQUEST = 'USER_LOGIN_GOOGLE_REQUEST'
export const USER_LOGIN_GOOGLE_SUCCESS = 'USER_LOGIN_GOOGLE_SUCCESS'
export const USER_LOGIN_GOOGLE_FAIL = 'USER_LOGIN_GOOGLE_FAIL'
export const USER_LOGOUT_GOOGLE = 'USER_LOGOUT_GOOGLE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const NOTIFICATION_ORDER = 'NOTIFICATION_ORDER'
export const NOTIFICATION_ORDER_SUCCESS = 'NOTIFICATION_ORDER_SUCCESS'
export const NOTIFICATION_ORDER_FAIL = 'NOTIFICATION_ORDER_FAIL'

export const NOTIFICATION_API_ORDER = 'NOTIFICATION_API_ORDER'
export const NOTIFICATION_API_ORDER_SUCCESS = 'NOTIFICATION_API_ORDER_SUCCESS'
export const NOTIFICATION_API_ORDER_FAIL = 'NOTIFICATION_API_ORDER_FAIL'

export const USER_DELETE_ADDRESS_REQUEST = 'USER_DELETE_ADDRESS_REQUEST'
export const USER_DELETE_ADDRESS_SUCCESS = 'USER_DELETE_ADDRESS_SUCCESS'
export const USER_DELETE_ADDRESS_FAIL = 'USER_DELETE_ADDRESS_FAIL'

export const USER_CREATE_ADDRESS_REQUEST = 'USER_CREATE_ADDRESS_REQUEST'
export const USER_CREATE_ADDRESS_SUCCESS = 'USER_CREATE_ADDRESS_SUCCESS'
export const USER_CREATE_ADDRESS_FAIL = 'USER_CREATE_ADDRESS_FAIL'

export const USER_EDIT_ADDRESS_REQUEST = 'USER_EDIT_ADDRESS_REQUEST'
export const USER_EDIT_ADDRESS_SUCCESS = 'USER_EDIT_ADDRESS_SUCCESS'
export const USER_EDIT_ADDRESS_FAIL = 'USER_EDIT_ADDRESS_FAIL'

export const USER_SELECT_ROLE_REQUEST = 'USER_SELECT_ROLE_REQUEST'
export const USER_SELECT_ROLE_SUCCESS = 'USER_SELECT_ROLE_SUCCESS'
export const USER_SELECT_ROLE_FAIL = 'USER_SELECT_ROLE_FAIL'

export const SHIPPER_LOGIN_REQUEST = 'SHIPPER_LOGIN_REQUEST'
export const SHIPPER_LOGIN_SUCCESS = 'SHIPPER_LOGIN_SUCCESS'
export const SHIPPER_LOGIN_FAIL = 'SHIPPER_LOGIN_FAIL'
